# Generated by Django 5.0.2 on 2024-11-20 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=255)),
                ('author_dis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=255)),
                ('book_dis', models.CharField(max_length=255)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='home.author')),
            ],
        ),
    ]
